base_url: "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/"

layers:
    - name: "ne_10m_admin_0_countries"
      type: "cultural"
      start_zoom: 0
      end_zoom: 4
    - name: "ne_10m_admin_1_states_provinces"
      type: "cultural"
      start_zoom: 4
      end_zoom: "g"
    - name: "ne_10m_ocean"
      type: "physical"
      start_zoom: 0
      end_zoom: "g"
    - name: "ne_10m_land"
      type: "physical"
      start_zoom: 0
      end_zoom: "g"
    - name: "ne_10m_rivers_lake_centerlines_scale_rank"
      type: "physical"
      start_zoom: 0
      end_zoom: "g"
    - name: "ne_10m_lakes"
      type: "physical"
      start_zoom: 0
      end_zoom: "g"
    - name: "ne_10m_admin_0_disputed_areas"
      type: "cultural"
      start_zoom: 4
      end_zoom: "g"
    - name: "ne_10m_populated_places"
      type: "cultural"
      start_zoom: 5
      end_zoom: "g"
    - name: "ne_10m_roads"
      type: "cultural"
      start_zoom: 5
      end_zoom: "g"
    - name: "ne_10m_time_zones"
      type: "cultural"
      start_zoom: 0
      end_zoom: 2
